name: CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      working-directory: capstone_project/hello-world/
      run: npm ci

    - name: Run tests
      working-directory: capstone_project/hello-world/
      run: npm test

    - name: Build Docker image
      working-directory: capstone_project/hello-world/
      if: success()
      run: docker build -t my-hello-world-app .

